### ISSUE TITLE
Fork to lfex

### ISSUE THREAD

**Issue by yurrriq** [quasiquoting/lodox#35]

**Comment by yurrriq** [comment]
Or maybe transfer?

**Comment by arpunk** [comment]
@yurrriq As far as I'm concerned, this should be on my daily workflow. +1 for lfex

**Comment by yurrriq** [comment]
:smile: Thanks for the positive feedback.

There are [a few more things I want to do before 1.0.0](https://github.com/quasiquoting/lodox/milestones/1.0.0), but after that I'll feel ready to fork.

**Comment by yurrriq** [comment]
Thanks, @oubiwann!
