### ISSUE TITLE
Can't get lodox running in a project

### ISSUE THREAD

**Issue by oubiwann** [quasiquoting/lodox#38]
Hey @yurrriq, do you have an example of a project using lodox?

I'm not able to get it working. Partial output from `rebra3`:

```
===> Compiling lodox
 ~~>    Finding .lfe files ...
 ~~>    Compiling ./_build/default/plugins/lodox/src/lodox-html-writer.lfe ...
===> Plugin {lodox,".*",
                          {git,"git://github.com/quasiquoting/lodox.git",
                               {tag,"0.9.0"}}} not available. It will not be used.
```

In other words, it doesn't compile all the lodox `.lfe` files ...

The project where I'm attempting this is here:
- https://github.com/oubiwann/lgeo

**Comment by yurrriq** [comment]
Weird. I'll take a look but that seems like the right config to me..

**Comment by yurrriq** [comment]
I've used it in private projects just fine. I've also had success with installing it globally. I'll clone lgeo when I get home and see if I can figure it out.

**Comment by yurrriq** [comment]
After cloning, `brew install gdal`, disabling my global `lodox` config (in `~/.config/rebar3/rebar.config`) I'm able to generate documentation without issue...

Partial output from `rebar3 lodox`:

``` erlang
===> Fetching lodox ({git,"git://github.com/quasiquoting/lodox.git",
                                 {tag,"0.9.0"}})
...
===> Compiling lodox
~~~>    Finding .lfe files ...
~~~>    Compiling ./_build/default/plugins/lodox/src/lodox-html-writer.lfe ...
~~~>    Compiling ./_build/default/plugins/lodox/src/lodox-p.lfe ...
~~~>    Compiling ./_build/default/plugins/lodox/src/lodox-parse.lfe ...
~~~>    Compiling ./_build/default/plugins/lodox/src/lodox-util.lfe ...
~~~>    Compiling ./_build/default/plugins/lodox/src/lodox.lfe ...
~~~>    Compiling ./_build/default/plugins/lodox/test/unit-lodox-tests.lfe ...
...
Generated lgeo v0.2.0 docs in /path/to/oubiwann/lgeo/doc
```

**Comment by yurrriq** [comment]
Maybe it was a temporary GitHub issue. FWIW you should use `"0.10.0"` now :smile:

**Comment by yurrriq** [comment]
It may also be worth trying `https://` instead of `git://`.

**Comment by oubiwann** [comment]
Yeah, I had started with 0.10.0, and backed down to 0.9.0, in case it was a new issue introduced in the latest version. I switched to https, bumped it back up to 0.10.0 -- no joy.

Not sure what's going on, but I'll try to look at it more ... I'll keep this ticket open and update with my findings.

Thanks for giving it a try, and confirming that you could run it on another project!

**Comment by yurrriq** [comment]
Hmm... I've pushed a couple new versions since then, notably changing the invocation to `rebar3 lfe lodox`, but this seems to be more of a "get the plugin" rather than runtime issue.

Sounds good. Keep us posted. I hope it works out soon.

**Comment by oubiwann** [comment]
Well, this ended up being an unreported error with the Erlang ports I was building (code that hadn't been checked in yet, so you didn't see the problem). Trial and error finally got me to a solution, which -- as you have suspected -- had nothing to do with lodox :-)

lodox is building now -- looking great! Super-excited about it! Thanks again for doing it :-) :+1:

**Comment by yurrriq** [comment]
Awesome! Thanks for using it.

**Comment by oubiwann** [comment]
I hit this again later, so I'm leaving a note for myself and anyone else who might come across this (again!): lodox requires a recent version of Erlang, 18.x or newer. 17.x won't work due to map usage (had to run `DEBUG=1 rebar3 lfe lodox` to figure this out).
