### ISSUE TITLE
Support for excluding modules?

### ISSUE THREAD

**Issue by oubiwann** [quasiquoting/lodox#42]
There are some modules I won't want included in a public API (e.g., modules that bring in functions defined in C ports, for which there are friendlier, "public" modules).

Could you add a configuration file (or flag) option for excluding modules from the generated docs?

**Comment by yurrriq** [comment]
I'm working on a configuration revamp right now. How would you feel about something like this in the config:

``` erlang
{'excluded-modules',
  ['secret-mod', 'private-mod', 'excluded-mod']}
```

^ a list of module names to exclude.

**Comment by oubiwann** [comment]
Yeah, that's the sort of thing I was thinking.

If this goes in the `rebar.config` file (possible? I hope so...), I'd add lodox context, e.g.:

``` erlang
{lodox [{'excluded-modules',
         ['secret-mod','private-mod','exlcuded-mod']}]}.
```

This leaves a whole bunch of nice possibilities for lodox in the future (configurability for things we can't think of right now).

If rebar3 barfs on having extraneous data in `rebar.config`, I'd opt for using `lfe.config` ... since it'd be a shame to have a proliferation of configuration files in LFE projects ...

**Comment by yurrriq** [comment]
That's exactly what I've got cooking. :smile:

**Comment by oubiwann** [comment]
SWEEEEET! :neckbeard: :heart:

**Comment by yurrriq** [comment]
This needs to be cleaned up and documented, but the basic functionality is there.

**Comment by yurrriq** [comment]
- [ ] Include [this example](https://github.com/quasiquoting/lodox/issues/41#issuecomment-189949944)

**Comment by yurrriq** [comment]
Moved to lfe-rebar3/lodox#18.
