### ISSUE TITLE
Shell error in generated docs

### ISSUE THREAD

**Issue by oubiwann** [quasiquoting/lodox#43]
So, I spoke too soon about the docs I had generated for the lgeo project :-(

Turns out all the docstrings are rendered with this error instead of the actual docstrings:

```
/bin/sh: 1: Syntax error: redirection unexpected 
```

Here's a screenshot:

![lodox-screnshot](https://cloud.githubusercontent.com/assets/894251/12385546/fb9279e4-bd82-11e5-925a-717ba1844a11.png)

Note that I'm running on Linux, not Mac OS X ... (there are differences in how they handle redirection).

**Comment by yurrriq** [comment]
Yikes. The `pandoc` usage is pretty hacky atm. In an ideal world, I'd write a Haskell port and interface with it directly. The offending code is [here](https://github.com/quasiquoting/lodox/blob/0.12.1/src/lodox-html-writer.lfe#L86).

@oubiwann and anyone else reading this, do you have experience writing a Haskell port? Can it be done? Or, is there a better, more platform-independent way to "shell out" to `pandoc`?

**Comment by oubiwann** [comment]
Hrm, I think `(os:cmd)` should be just fine. Unfortunately, to debug this we'll have to break up the pretty thrushing :-( 'cause we'll need to see what command is getting generated in Linux.

At the risk of throwing more engineering at the problem, it may be worth setting up lodox to use logjam ... this would allow for easier debugging be interested parties.

If you like that idea, we can open a feature ticket, and I'll get that running so that this issue (and future ones) may be more easily debugged ... it will mean adding an `lfe.config` file, though (since that's what logjam uses ...)

**Comment by yurrriq** [comment]
logjam could be cool.

**Comment by yurrriq** [comment]
Re: breaking up thrushing. `doto` (or the `!` arrows in pynchon) to the rescue!

Something like the following should get the job done. (At work now, so I can't fully dive in...)

``` lfe
(->> `[,pandoc ,(escape markdown)]
                 (doto (io_lib:format "~s -f markdown_github -t html <<< \"~s\"")
                   (->> (list) (io:fwrite "** PANDOC CMD: ~p~n")))
                 (lists:flatten)
                 (os:cmd))
```

**Comment by oubiwann** [comment]
Oooh, that sounds interesting. I'd like to see that in action!

**Comment by oubiwann** [comment]
Okay, so two problems, one minor.

1) The following :

``` cl
(io_lib:format "~s -f markdown_github -t html <<< \"~s\"")
```

needs to be changed to this:

``` cl
(io_lib:format "~s -f markdown_github -t html <<< '~s'")
```

That will prevent Bash from barfind on parens that are in the here-string.

2) This one's trickier. It seems that `sh` is  what is used on Linux when calling `#'os:cmd/1` and `sh` doesn't understand here-strings on Linux. I got around this by changing the command to `"bash -c \"~s\"" `(,cmd))"`. Worked like a charm. However, when I tried to build the command in pieces using `#io_lib:format/2`, `#'os:cmd/1` reverted to using`sh`(or something else happened) and it gave the redirection error again. The only way I was able to get this to work was by assembling the`cmd`string with`++``. 

Some examples will illustrate the problem.

Current, broken (on Linux) behaviour:

``` cl
> (os:cmd "/usr/bin/pandoc -f markdown_github -t html <<< '\\`\\`\\`commonlisp\n(_SRS)\n\\`\\`\\`'")
"/bin/sh: 1: Syntax error: redirection unexpected\n"
```

Getting it to work with `bash -c`:

``` cl
> (os:cmd "bash -c \"/usr/bin/pandoc -f markdown_github -t html <<< '\\`\\`\\`commonlisp\n(_SRS)\n\\`\\`\\`'\"")
"<pre class=\"sourceCode commonlisp\">
<code class=\"sourceCode commonlisp\">(_SRS)</code>
</pre>\n"
```

Parameterizing the `bash -c` solution:

``` cl
> (set cmd "/usr/bin/pandoc -f markdown_github -t html <<< '\\`\\`\\`commonlisp\n(_SRS)\n\\`\\`\\`'")
"/usr/bin/pandoc -f markdown_github -t html <<< '\\`\\`\\`commonlisp\n(_SRS)\n\\`\\`\\`'"
> (os:cmd (lists:flatten (io_lib:format "bash -c ~s" `(,cmd))))
"/bin/sh: 1: Syntax error: redirection unexpected\n"
> (os:cmd (++ "bash -c \"" cmd "\""))              
"<pre class=\"sourceCode commonlisp\">
<code class=\"sourceCode commonlisp\">(_SRS)</code>
</pre>\n"
```

I'm not submitting a patch for this due to the fact that there are all sorts of ways one might solve this, but the most obvious that works (appending strings) breaks your style (e.g., you won't be able to use the `->>` thrushing macro without adding a wrapper functions that takes the args in the appropriate positions).

The approach that I might take would be to define `#'bash-cmd/1` and it would append the strings and call `#'os:cmd/``, thus letting you thrush away. This will likely be pretty fragile (though I can't think of a quick, non-fragile work-around), and you may have other ideas ...

**Comment by yurrriq** [comment]
Thanks for looking into it further. Seems like a tricky, platform specific issue.. `bash -c` would break on Windows, right?

It seems like writing to temp files would work but that's kind of a last resort. I may explore writing a Haskell port since that sounds fun anyway.

Maybe a cone on host type with platform-specific solutions will suffice for now.

**Comment by yurrriq** [comment]
:+1: for bash-cmd for now though.

**Comment by yurrriq** [comment]
``` erlang
(io_lib:format "~s -f markdown_github -t html <<< '~s'")
```

breaks code blocks and more, for me.

**Comment by yurrriq** [comment]
TIL here strings write to a temporary file anyway, so I'm doing it manually with some promising initial success.

**Comment by yurrriq** [comment]
@oubiwann, could you pull develop and try it? In case I push more code, the commit I mean for you to try is 7fee1e4a32293f73bfa133364c5aad36538f2093.

**Comment by yurrriq** [comment]
^ includes some config overhaul see [`rebar.config`](https://github.com/quasiquoting/lodox/blob/448e53a05298d6a45b6dc8c6ce5ad272f5b9e8c3/rebar.config#L23-L27) for an example.

I'm not married to `apps` at the top level, but it works nicely when a project has multiple apps.

**Comment by yurrriq** [comment]
Pasted example for convenience:

``` erlang
{lodox,
 [{apps,
   [{lodox,
     [{'source-uri',
       "https://github.com/quasiquoting/lodox/blob/{version}/{filepath}#L{line}"},
      {'output-path', "relative/path/to/output"}]}]}]}.
```

N.B. `output-path` is taken literally, for now, so `{version}` won't do anything.

**Comment by yurrriq** [comment]
^ oops, broken for now

**Comment by yurrriq** [comment]
`{version}` should work in develop.

**Comment by yurrriq** [comment]
@oubiwann, does [0.12.5](https://github.com/quasiquoting/lodox/releases/tag/0.12.5) work for you?
