### ISSUE TITLE
Support user links

### ISSUE THREAD

**Issue by oubiwann** [quasiquoting/lodox#44]
Hey! Guess what! Another feature request for ya ;-)

So I hacked up the lodox source per the solution I outlined in issue #43  and am publishing it (with some `Makefile` work-arounds for output dir) on the project gh-pages under `/api`:
- https://github.com/oubiwann/lgeo#documentation-

What would be nice, though, is if I could add my own links at the top and/or bottom of the docs nav. This would allow users a nice way of getting back to the project site on Github or the user-guide slate docs. I'd like to put one or two important links above everything else in the left nav, and then put minor links below the last entry in the left nav, probably with a CSS border for visual separation.

My first thought for supporting this would be two configuration directives in the lodox entry, e.g.:

``` erlang
{lodox [{'top-links',
         [[{text,"My Project"},{url,"http://project.com"}],
          [{text,"User Guide"},{url,"http://guide.project.com"}]]},
        {'bottom-links',
         [[{text,"Related Project"},{url,"http://other.com"}],
          [{text,"LFE"},{url,"http://github.com/rvirding/lfe"}]]}
]}.
```

**Comment by yurrriq** [comment]
Cool idea. Codox has support for "topics," though I've not used it myself. Maybe this is analogous.

**Comment by yurrriq** [comment]
Closing in favor of #48.
