### ISSUE TITLE
Handle macro-generated functions

### ISSUE THREAD

**Issue by yurrriq** [quasiquoting/lodox#49]
Now that macros are getting more meta, we should probably somehow parse `defun`s that are generated by macros at compile time. @rvirding, could you remind me of the option to pass to the compiler to return the macro-expanded forms?

**Comment by rvirding** [comment]
OK, so a macro can only expand to one form, there is no way around this. If you would like to expand to multiple forms _at top-level_ in a module then you can return them in a `(progn ...)` which the compiler accepts and flattens. So you can do `(my-macro ...)` ==> `(progn <form-1> <form-2> ...)` where the forms can be new function/macro definitions.

As an example try doing `(macroexpand '(defrecord foo a b))` in the REPL.

**Comment by yurrriq** [comment]
Right. I just need a way to access (and then parse via lodox) the generated forms, even if they're wrapped in `progn`s. Right now, lodox just sees `(my-macro ...)` and moves on.

**Comment by rvirding** [comment]
You could call the compiler to expand all the top-level macros, or all macros, and then process that. It would also split the file into separate modules.

**Comment by yurrriq** [comment]
iirc there was a certain option to pass to get expanded macros back..

**Comment by rvirding** [comment]
`(lfe_compile:file "file.lfe" '(to-split binary))` expands the top-level macros and splits the file into separate modules. The `to-umac` option expands generates the functions to handle exported macros and the `to-exp` option fully expands all macros. The `binary` option returns the resulting code as a data structure; without it the output is written into files.

This interface will most likely not change in the future.

**Comment by quasiquote** [comment]
Perfect! Thank you.

**Comment by yurrriq** [comment]
Perfect! Thank you.

**Comment by yurrriq** [comment]
Will be solved by #58.
