### ISSUE TITLE
Circular dependency with levaindoc

### ISSUE THREAD

**Issue by oubiwann** [quasiquoting/lodox#54]
With the release of lodox 0.12.6 it seems that a circular dependency crept in. I had to downgrade back to 0.12.5.

**Comment by yurrriq** [comment]
Yeah, I'm not sure exactly what's going on here, but 0.12.5 is definitely the one to use. I'll take a look back in MN.

**Comment by yurrriq** [comment]
This should be fixed in 0.12.8. I'll try to confirm tomorrow.

**Comment by yurrriq** [comment]
Seems to work or me. Closing until proven wrong.
