### ISSUE TITLE
Odd behaviour with rebar3 profiles

### ISSUE THREAD

**Issue by oubiwann** [quasiquoting/lodox#55]
You love all these bug reports, right? :-D

So, I don't know if this is a problem in _general_ or if it's just because examplar is also a dep of lodox ...

Anyway, when I used rebar3 profiles in the exemplar project and put lodox in a `docs` profile, it no longer rendered the docs for the examplar project source at version 0.3.2 (for which I was running lodox), but instead used the source code from the exemplar dependency that lodox has (0.3.0).

As soon as I took the lodox dep out of the profile and just put it in the top-level, default of the rebar.config, it did the right thing and processes the project's docs (instead of the dependencies).

This might even be a bug in rebar3 ...

**Comment by yurrriq** [comment]
Of course! I've had some similarly weird experiences with generating lodox's own documentation. I settled on a manual invocation you can find in the literate org/README.org. I wonder if there's a hack around it... I'll hit up #rebar on IRC soon and try to figure it out.

**Comment by yurrriq** [comment]
This is solved now by running `lodox` in the `doc` profile.
